/* Origin V8 provider router — MobileAPI first, unofficial GSMArena fallback. */
(function () {
  'use strict';
  const PROXY = '/api/mobileapi';
  const GSMARENA = '/api/gsmarena';
  const TTL = 10 * 60 * 1000;
  async function mobile(path) {
    const r = await fetch(PROXY + path, { headers:{Accept:'application/json'}, cache:'no-store' });
    const text = await r.text(); let d={}; try{d=text?JSON.parse(text):{}}catch(_){throw Error(`MobileAPI returned non-JSON (HTTP ${r.status}).`)}
    if(!r.ok) throw Error(d?.detail||d?.error||`MobileAPI HTTP ${r.status}`); return d;
  }
  async function gsma(path) {
    const r = await fetch(GSMARENA + path, { headers:{Accept:'application/json'}, cache:'no-store' });
    const text = await r.text(); let d={}; try{d=text?JSON.parse(text):{}}catch(_){throw Error(`GSMArena returned non-JSON (HTTP ${r.status}).`)}
    if(!r.ok) throw Error(d?.detail||d?.error||`GSMArena HTTP ${r.status}`); return d;
  }
  const rows=d=>Array.isArray(d)?d:d?.results||d?.data?.results||d?.devices||d?.data?.devices||d?.data||[];
  const name=x=>x?.name||x?.model_name||x?.model||x?.device_name||x?.title||'Unknown device';
  const id=x=>x?.id??x?.device_id??x?.pk??'';
  const brand=x=>x?.manufacturer?.name||x?.manufacturer||x?.brand?.name||x?.brand||'';
  const summary=x=>[brand(x),x?.release_date||x?.releaseDate,x?.display?.size||x?.screen_size,x?.platform?.chipset||x?.chipset,x?.memory?.ram||x?.ram].filter(Boolean).slice(0,5).join(' · ');
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  async function search(q){try{const d=await mobile(`/devices/search/?name=${encodeURIComponent(q)}&page=1`);return rows(d).map(x=>({name:name(x),id:id(x),raw:x,summary:summary(x),provider:'MobileAPI'})).filter(x=>x.id!==''&&x.name!=='Unknown device')}catch(_){return []}}
  async function fallback(q){try{const d=await gsma(`/search?q=${encodeURIComponent(q)}`);return rows(d).map(x=>({name:x.name||'Unknown device',id:x.slug,raw:x,summary:'GSMArena · unofficial fallback',provider:'GSMArena'})).filter(x=>x.id)}catch(_){return []}}
  let modal;
  function make(){if(modal)return modal;modal=document.createElement('div');modal.className='origin-v6-modal';modal.hidden=true;modal.innerHTML='<div class="origin-v6-backdrop"></div><section class="origin-v6-sheet"><button class="origin-v6-close">×</button><div class="origin-v6-kicker">ORIGIN · LIVE DEVICE DATA</div><div class="origin-v6-heading"><div><h2 data-title></h2><p data-subtitle></p></div><span class="origin-v6-live">● LIVE</span></div><div data-content></div></section></div>';document.body.appendChild(modal);const close=()=>{modal.classList.remove('open');document.body.classList.remove('origin-v6-open');setTimeout(()=>modal.hidden=true,180)};modal.querySelector('.origin-v6-close').onclick=close;modal.querySelector('.origin-v6-backdrop').onclick=close;return modal}
  function open(){const m=make();m.hidden=false;requestAnimationFrame(()=>m.classList.add('open'));document.body.classList.add('origin-v6-open')}
  function flatten(v,p='',a=[],d=0){if(d>14||v==null||v==='')return;if(typeof v!=='object'){a.push([p||'Specification',String(v)]);return}if(Array.isArray(v)){v.forEach((x,i)=>flatten(x,`${p||'Item'} ${i+1}`,a,d+1));return}Object.keys(v).forEach(k=>flatten(v[k],p?`${p} · ${k}`:k,a,d+1))}
  const specs=d=>{const a=[];flatten(d.__gsma?{specifications:d.specifications}:d,'',a);const f=a.filter(([k,v])=>!/(image|thumbnail|url|base64|source_url)/i.test(k)&&v.length<2000);return f.length?`<div class="origin-v6-specs">${f.map(([k,v])=>`<div><span>${esc(k.replace(/[_-]+/g,' '))}</span><strong>${esc(v)}</strong></div>`).join('')}</div>`:'<div class="origin-v6-empty">No displayable specifications were returned.</div>'};
  const image=x=>x?.image?.url||x?.image_url||x?.thumbnail||x?.images?.[0]?.url||x?.images?.[0]||x?.device_image||x?.image||'';
  async function detail(m){if(m.provider==='GSMArena')return {__gsma:true,...await gsma(`/device?slug=${encodeURIComponent(m.id)}`)};const i=m.id;const d=await mobile(`/devices/${encodeURIComponent(i)}/`);return d?.data?.device||d?.device||d?.data||d}
  async function showModel(company,m){const c=make(),out=c.querySelector('[data-content]');c.querySelector('[data-title]').textContent=m.name;c.querySelector('[data-subtitle]').textContent=`${company} · ${m.provider}`;out.innerHTML='<div class="origin-v6-loading"><strong>Fetching complete specifications…</strong><span>Live provider record</span></div>';open();try{const d=await detail(m),img=image(d)||image(m.raw);out.innerHTML=(img?`<div class="origin-v6-device-image"><img src="${esc(img)}" alt="${esc(m.name)}"></div>`:'')+`<div class="origin-v6-bar"><strong>FULL SPECIFICATIONS</strong><span>${esc(m.provider)}</span></div>`+specs(d)+`<p class="origin-v6-note">GSMArena data is an unofficial fallback and is not affiliated with Origin.</p>`}catch(e){out.innerHTML=`<div class="origin-v6-error"><strong>Specifications could not be fetched.</strong><p>${esc(e.message)}</p></div>`}}
  async function showProduct(company,product){const c=make(),out=c.querySelector('[data-content]');c.querySelector('[data-title]').textContent=product;c.querySelector('[data-subtitle]').textContent=`${company} · MobileAPI first · GSMArena fallback`;out.innerHTML='<div class="origin-v6-loading"><strong>Searching live device databases…</strong><span>MobileAPI.dev first, GSMArena only when no MobileAPI match exists</span></div>';open();let ms=await search(`${company} ${product}`);if(!ms.length)ms=await fallback(`${company} ${product}`);if(!ms.length){out.innerHTML='<div class="origin-v6-error"><strong>No matching device found.</strong><p>Neither provider returned a matching device.</p></div>';return}out.innerHTML=`<div class="origin-v6-status"><strong>${ms.length} matching devices</strong><span>${esc(ms[0].provider)}</span></div><div class="origin-v6-models">${ms.slice(0,50).map((x,i)=>`<button data-model="${i}"><span class="origin-v6-num">${String(i+1).padStart(2,'0')}</span><div><strong>${esc(x.name)}</strong><small>${esc(x.summary||'Open full specifications')} · ${esc(x.provider)}</small></div><b>›</b></button>`).join('')}</div>`;out.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>showModel(company,ms[Number(b.dataset.model)]))}
  function bind(){const page=document.querySelector('#companyPage:not([hidden])');if(!page)return;const company=page.querySelector('.company-hero-copy h1')?.textContent?.trim()||'Company';page.querySelectorAll('.product-universe-card').forEach(card=>{if(card.dataset.originV8Bound)return;card.dataset.originV8Bound='1';card.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();showProduct(company,card.querySelector('strong')?.textContent?.trim()||card.textContent.trim())},true)})}
  const s=document.createElement('style');s.textContent='.origin-v6-open{overflow:hidden}.origin-v6-modal{position:fixed;inset:0;z-index:1400;background:rgba(17,17,17,.52);backdrop-filter:blur(18px);opacity:0;transition:.18s}.origin-v6-modal.open{opacity:1}.origin-v6-modal[hidden]{display:none}.origin-v6-sheet{position:absolute;inset:0;background:#f7f7f5;overflow:auto;padding:20px max(12px,calc((100% - 980px)/2)) 35px}.origin-v6-close{position:fixed;top:10px;right:10px;width:40px;height:40px;border:1px solid #deded9;border-radius:50%;background:#fff;font-size:24px;z-index:2}.origin-v6-kicker{font-size:10px;font-weight:850;letter-spacing:.14em;color:#6d5dfc;margin:10px 0 12px}.origin-v6-heading{display:flex;justify-content:space-between;gap:15px;margin-bottom:15px}.origin-v6-heading h2{margin:0;font-size:clamp(38px,7vw,72px);line-height:.98;letter-spacing:-.06em}.origin-v6-heading p{margin:7px 0;color:#777}.origin-v6-live{font-size:10px;background:#fff;border:1px solid #ddd;border-radius:999px;padding:8px;white-space:nowrap}.origin-v6-status,.origin-v6-bar{display:flex;justify-content:space-between;gap:8px;border-bottom:1px solid #ddd;padding:9px 0;margin-bottom:9px;font-size:12px}.origin-v6-models{display:grid;gap:6px}.origin-v6-models button{border:1px solid #ddd;background:#fff;border-radius:12px;padding:9px;display:grid;grid-template-columns:42px 1fr 16px;gap:9px;align-items:center;text-align:left}.origin-v6-num{width:42px;height:42px;border-radius:9px;background:#111;color:#fff;display:grid;place-items:center;font-size:10px}.origin-v6-models strong{display:block;font-size:13px}.origin-v6-models small{display:block;color:#777;font-size:10px;margin-top:3px}.origin-v6-loading,.origin-v6-error,.origin-v6-empty{border:1px dashed #ddd;border-radius:13px;background:#fff;padding:22px;text-align:center}.origin-v6-loading span,.origin-v6-error p{display:block;color:#777;font-size:12px;margin-top:6px}.origin-v6-device-image{border:1px solid #ddd;border-radius:14px;background:#fff;padding:12px;text-align:center;margin-bottom:10px}.origin-v6-device-image img{max-width:100%;max-height:320px;object-fit:contain}.origin-v6-specs{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:1px;background:#ddd;border:1px solid #ddd;border-radius:13px;overflow:hidden}.origin-v6-specs>div{background:#fff;padding:10px 12px}.origin-v6-specs span{display:block;color:#888;font-size:9px;text-transform:uppercase;margin-bottom:4px}.origin-v6-specs strong{font-size:12px;line-height:1.4}.origin-v6-note{color:#888;font-size:10px}@media(max-width:600px){.origin-v6-heading{display:block}.origin-v6-heading h2{font-size:42px}.origin-v6-live{display:inline-block;margin-top:8px}.origin-v6-specs{grid-template-columns:1fr}}';document.head.appendChild(s);new MutationObserver(bind).observe(document.body,{subtree:true,childList:true});bind();
})();
